services:
  # Shared infrastructure services
  message-broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - inventory-system-network

  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - inventory-system-network
    depends_on:
      - inventory-service
      - warehouse-service
      - order-service
      - supplier-service
      - user-service

  # Independent service containers using their own docker-compose files
  inventory-service:
    build:
      context: ./services/inventory-service
      dockerfile: Dockerfile
    networks:
      - inventory-system-network
    depends_on:
      - message-broker

  warehouse-service:
    build:
      context: ./services/warehouse-service
      dockerfile: Dockerfile
    networks:
      - inventory-system-network
    depends_on:
      - message-broker

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    networks:
      - inventory-system-network
    depends_on:
      - message-broker

  supplier-service:
    build:
      context: ./services/supplier-service
      dockerfile: Dockerfile
    networks:
      - inventory-system-network
    depends_on:
      - message-broker

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    networks:
      - inventory-system-network
    depends_on:
      - message-broker

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    networks:
      - inventory-system-network
    depends_on:
      - message-broker

  analytics-service:
    build:
      context: ./services/analytics-service
      dockerfile: Dockerfile
    networks:
      - inventory-system-network
    depends_on:
      - message-broker

networks:
  inventory-system-network:
    driver: bridge

volumes:
  rabbitmq-data:
