x-common-variables: &common-variables
  POSTGRES_SERVER: db
  REDIS_URL: redis://redis:6379/0

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    container_name: invman_server_${ENVIRONMENT}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.${ENVIRONMENT}
    entrypoint: ./scripts/entrypoint-${ENVIRONMENT}.sh
    environment:
      <<: *common-variables
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - .:/app

  db:
    image: postgres:alpine
    container_name: invman_db_${ENVIRONMENT}
    env_file:
      - .env.${ENVIRONMENT}
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./generate-sql.sh:/docker-entrypoint-initdb.d/generate-sql.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    container_name: "invman_cache_${ENVIRONMENT}"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
